### ISSUE TITLE
Uboot not compile with dtc 1.4.6.1 and later

### ISSUE THREAD

**Issue by giutrec** [orangepi-xunlong/OrangePiH6_uboot#1]
Hi, i've looks a little problem the uboot not compile with dtc version 1.4.6.1 and later but works correctly with 1.4.5.1
The official repo have made a patch, please see this discussion
https://lists.denx.de/pipermail/u-boot/2017-May/293269.html

Regards!

**Comment by orangepi-xunlong** [comment]
Thanks, now the DTC program has been moved to the external folder so you don't have to worry about the version installed on the PC.
